src/Warsaw.Notifications.Web/Models/ErrorViewModel.cs
using System;

namespace Warsaw.Notifications.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Warsaw.Notifications.Web/Models/NotificationViewModel.cs
using System;
using System.Collections.Generic;

namespace Warsaw.Notifications.Web.Models 
{
    public class NotificationViewModel 
    {
        public string Category { get; set; }
        public string City { get; set; }
        public string Subcategory { get; set; }
        public string District { get; set; }
        public string NotificationType { get; set; }
        public DateTime CreateDate { get; set; }
        public string Source { get; set; }
        public string Street { get; set; }
        public string DeviceType { get; set; }
        public string NotificationNumber { get; set; }
        public string Event { get; set; }
    }
}

src/Warsaw.Notifications.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace Warsaw.Notifications.Web.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            
        }
    }
}

src/Warsaw.Notifications.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Warsaw.Notifications.Web.Models;

namespace Warsaw.Notifications.Web.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Deployment()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Warsaw.Notifications.Web/Controllers/NotificationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Warsaw.Notifications.Domain.Components;
using Warsaw.Notifications.Domain.Components.Models;
using Warsaw.Notifications.Web.Models;

namespace Warsaw.Notifications.Web.Controllers {
    public class NotificationController : BaseController {
        private readonly INotificationSystem _notificationSystem;
        private readonly IMapper _mapper;

        public NotificationController (INotificationSystem notificationSystem, IMapper mapper)
        { 
            _notificationSystem = notificationSystem;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index() 
        {
            ViewBag.AvaliableDistricts = await _notificationSystem.GetAvaliableDistrictsAsync();
            return View();
        }

        [Route ("Notification/Search/{districtName}")]
        public async Task<IActionResult> Search(string districtName) 
        {
            var districts = await _notificationSystem.GetAvaliableDistrictsAsync();
            var district = districts.SingleOrDefault(d => d.Name.Equals(districtName));

            ViewBag.District = district.Name;
            var notificationsRaw = await _notificationSystem.GetNotificationsForDistrictAsync(district);
            var notifications = _mapper.Map<List<NotificationViewModel>>(notificationsRaw);
            return View (notifications);
        }
    }
}

src/Warsaw.Notifications.Web/Views/Home/Contact.cshtml
<address class="top-buffer">
    Rafał Pieńkowski<br />
    <hr />
    <div class="top-buffer">
        <a href="https://github.com/rafalpienkowski/">Github <i class="fab fa-github"></i></a><br />
        <a href="https://www.linkedin.com/in/rafal-pienkowski/">LinkedIn <i class="fab fa-linkedin-in"></i></a><br />
        <a href="https://www.rafalpienkowski.pl/">Blog <i class="fas fa-book"></i></a><br />
    </div>
</address>

<address>
    <strong>Contact:</strong> <a class="disable-loading" href="mailto:rafal.pienkowski@wp.pl">rafal.pienkowski@wp.pl</a><br />
</address>

src/Warsaw.Notifications.Web/Views/Home/Deployment.cshtml
<div class="row">
    <div class="col-md-12 top-buffer">
        To deploy the application to the Azure you to perform following steps.
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h4>Prerequisites:</h4>
        <i class="fas fa-angle-right"></i> Azure Subscription <br />
        <i class="fas fa-angle-right"></i> <a href="https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest">Azure CLI installed on local machine</a> <br />
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <h4>Steps:</h4>
        <i class="fas fa-angle-right"></i> Login to the Azure <br/>
        <blockquote><pre><code>
            az login
        </code></pre></blockquote>
        <b>Note:</b><br/>
        There shoule pop up a default browser window and prompt for Azure portal credentials.
    </div>
</div>
<div class="row">
    <div class="col-md-12 top-buffer">
        <i class="fas fa-angle-right"></i> (Optional) In case of multiple Subscriptions set the proper one by<br/>
        <blockquote><pre><code>
            az account set --subscription &lt;&lt;SubscriptionId&gt;&gt; 
        </code></pre></blockquote>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <i class="fas fa-angle-right"></i> Create Resource Group <br/>
        <div>
            <blockquote><pre><code>
            az group create --name &lt;&lt;Resource group name&gt;&gt; --location &lt;&lt;Resource group location&gt;&gt;
            </code></pre></blockquote>
            <i>Example:</i><br />
            <blockquote><code>
            az group create --name my-resource-group --location westeurope
            </code></blockquote>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <i class="fas fa-angle-right"></i> Prepare parameters file <br/>
        <div class="top-buffer">
            <p>
                Before the depoly of the application you have to set up following parameters:
            </p>
            <ul>
                <li>siteName - Name of the site. It should be unique inside Azure</li>
                <li>serviceOwner - Name of the Service Owner. Default value: rafal.pienkowski</li>
                <li>warsawApiKey - Warsaw API key used for authentication purposes</li>
                <li>environmentType - Environment Type. Default value: dev</li>
                <li>sku - SKU. Default value: F1. <a href="https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms#SkuDescription">More details</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <i class="fas fa-angle-right"></i> Deploy resources <br/>
        <div>
            <blockquote><pre><code>
            az group deployment create -g &lt;&lt;Resource Group Name&gt;&gt; --template-file azuredeploy.json --parameters azuredeploy.parameters.json --name &lt;&lt;Name of deployment&gt;&gt; 
            </code></pre></blockquote>
            <i>Example:</i><br />
            <blockquote><code>
            az group deployment create -g my-resource-group --template-file azuredeploy.json --parameters azuredeploy.parameters.json--name deploy1
            </code></blockquote>
            ARM Template and example parameters could be found in my Github repo under following urls: <br />
            <ul>
            <li><a href="https://github.com/rafalpienkowski/warsaw-19115-notofications/blob/master/deploy/azuredeploy.json"><i class="fab fa-github"></i> azuredeploy.json</a></li>
            <li><a href="https://github.com/rafalpienkowski/warsaw-19115-notofications/blob/master/deploy/azuredeploy.parameters.json"><i class="fab fa-github"></i> azuredeploy.parameters.json</a></li>
            </ul>
        </div>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">  
        <i class="fas fa-angle-right"></i> Enjoy!<br/>
    </div>
</div>

src/Warsaw.Notifications.Web/Views/Home/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <h2>Warsaw 19115 Notification System</h2>
        <hr />
        <p>
            This simple system consumes data exposed by Miasto Stołeczne Warszawa (Url: http://api.um.warszawa.pl).
        </p>
        <p>
            This services shows all reported notifications for given district.
        </p>
        <p>
            To show notifications got to
            <a class="btn btn-default" asp-controller="Notification" asp-action="Index">Notifications</a>
        </p>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        The source code could be found in the <a href="https://github.com/rafalpienkowski/warsaw-19115-notofications"><i class="fab fa-github"></i> Github repository</a>.
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <h5>Technologies and libraries used to create this project:</h5>
        <i class="fas fa-angle-right"></i> <a href="https://www.microsoft.com/net/download">.Net Core 2.1</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.1">ASP.Net Core MVC</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://automapper.org/">Automapper</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://xunit.github.io/">XUnit</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://fluentassertions.com/">FluentAssertions</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://jquery.com/">JQuery</a><br />
        <i class="fas fa-angle-right"></i> <a href="http://getbootstrap.com/">Bootstrap 3</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://datatables.net/">DataTables</a><br />
        <i class="fas fa-angle-right"></i> <a href="https://fontawesome.com/">Font Awsome</a><br />
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <h5>Propositions of further improvements:</h5>
        <i class="fas fa-angle-double-right"></i> Authentication and authorization, e.g. <a href="https://oauth.net/2/">OAuth2</a><br />
        <i class="fas fa-angle-double-right"></i> Extended logging, e.g. integration with <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-overview">Azure Application Insights</a><br />
        <i class="fas fa-angle-double-right"></i> Api response cache (InMemory/Redis)<br />
        <i class="fas fa-angle-double-right"></i> Update of some packages like Bootstrap, JQuery<br />
    </div>
</div>  

src/Warsaw.Notifications.Web/Views/Notification/Index.cshtml
<h3>
    Please select on from currently avaliable districts and wait for results.
</h3>


<div class="row">
    <div class="col-md-12">
        <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="avaliableDistricts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Avaliable districts
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu" aria-labelledby="avaliableDistricts">
            @foreach (var district in ViewBag.AvaliableDistricts)
            {
                <li><a asp-controller="Notification" asp-action="Search" asp-route-id="@district.Name">@district.Name</a></li>
            }
        </ul>
        </div>
    </div>
</div>

src/Warsaw.Notifications.Web/Views/Notification/Search.cshtml
@using System.Linq
@model IEnumerable<NotificationViewModel>

<h2>
    Results for @ViewBag.District:
</h2>
<div class="row">
    <div class="col-md-12">
        <table id="search" class="table table-striped .table-hover">
            <thead>
                <tr>
                    <th>City</th>
                    <th>District</th>
                    <th>Street</th>
                    <th>Source</th>
                    <th>Notification Type</th>
                    <th>Notification Number</th>
                    <th>Create Date</th>
                    <th>Category</th>
                    <th>Subcategory</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.City</td>
                    <td>@item.District</td>
                    <td>@item.Street</td>
                    <td>@item.Source</td>
                    <td>@item.NotificationType</td>
                    <td>@item.NotificationNumber</td>
                    <td>@item.CreateDate</td>
                    <td>@item.Category</td>
                    <td>@item.Subcategory</td>
                </tr>
            }
            </tbody>
        </table>
    </div> 
</div>  


<div class="row top-buffer">
    <div class="col-md-12">
        <a class="btn btn-default" asp-controller="Notification" asp-action="Index">Back</a>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function(){
            $('#search').DataTable( {
                "order": [[ 0, "desc" ]]
            });
        });
    </script>
}

src/Warsaw.Notifications.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Warsaw 19115 Notifications</title>

    <environment include="Dev">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Dev">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Warsaw 19115 Notifications</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Notification" asp-action="Index">Notifications</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Deployment">Deployment</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content top-buffer">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Warsaw 19115 Notifications by Rafał Pieńkowski</p>
        </footer>
    </div>

    <div class="modal fade" id="loading" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>

    <environment include="Dev">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Dev">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
    $(document).ready(function(){
        $('a').click(function(event){
            if($(this).hasClass('disable-loading'))
            {
                return;
            }
            $('#loading').modal('show');
        });
    });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>